sudo: false

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      

before_install:
  - pip install --user cpp-coveralls


script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*"
  - coveralls --exclude "lib"

notifications:
  email: false
