sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      

before_install:
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest .

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"


notifications:
  email: false
