sudo: false

language:
  - cpp

compilers:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      

before_install:
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake ..
  - ./configure --enable-gcovs
  - cmake --build .
  - ctest .

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"


notifications:
  email: false
